language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - test=test-coverage

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]] || [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then test=test; fi

script:
  - composer $test

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
